CREATE TABLE `back-compre-local`.`comercio` (`ID` INT NOT NULL , `IMAGEM` VARCHAR(200) NOT NULL , `ENDERECO` VARCHAR(200) NOT NULL , `TELEFONE` VARCHAR(200) NOT NULL , `HORARIO_ENTRADA` VARCHAR(200) NOT NULL , `HORARIO_SAIDA` VARCHAR(200) NOT NULL , `HORARIO_ENTRADA_TARDE` VARCHAR(200) NOT NULL , `HORARIO_SAIDA_TARDE` VARCHAR(200) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `back-compre-local`.`frete` (`ID` INT NOT NULL , `ID_COMERCIO` INT NOT NULL , `DISTANCIA_MAXIMA` VARCHAR(200) NOT NULL , `TIPO` VARCHAR(200) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `back-compre-local`.`valor_frete` (`ID` INT NOT NULL , `ID_FRETE` INT NOT NULL , `VALOR` VARCHAR(200) NOT NULL , `DISTANCIA_LIMITE` VARCHAR(200) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `back-compre-local`.`produto` (`ID` INT NOT NULL , `ID_COMERCIO` INT NOT NULL , `NOME` VARCHAR NOT NULL , `IMAGEM` VARCHAR(200) NOT NULL , `PRECO` VARCHAR(200) NOT NULL , `ESTOQUE` VARCHAR(200) NOT NULL , `TIPO_VENDA` VARCHAR(20) NOT NULL , PRIMARY KEY (`ID`));
CREATE TABLE `back-compre-local`.`venda` (`ID` INT NOT NULL , `ID_COMERCIO` INT NOT NULL , `ID_PRODUTO` INT NOT NULL , `TIPO` VARCHAR(200) NOT NULL , `VALOR` VARCHAR(200) NOT NULL , `DATA_PEDIDO` VARCHAR(200) NOT NULL , `DATA_ENTREGA` VARCHAR(200) NOT NULL , `VOLUME` VARCHAR(200) NOT NULL , `QUANTIDADE` VARCHAR(200) NOT NULL , `PAGAMENTO` VARCHAR(200) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;


/*INSERT*/
INSERT INTO `comercio` (`ID`, `IMAGEM`, `ENDERECO`, `TELEFONE`, `HORARIO_ENTRADA`, `HORARIO_SAIDA`, `HORARIO_ENTRADA_TARDE`, `HORARIO_SAIDA_TARDE`) VALUES ('1', 'capim_conveniencia', 'Rua dos trabalhadores, 130', '99-99999999', '08:00', '12:00', '13:00', '18:00');
INSERT INTO `frete` (`ID`, `ID_COMERCIO`, `DISTANCIA_MAXIMA`, `TIPO`) VALUES ('1', '1', '10 km', 'Tava variável');
INSERT INTO `produto` (`ID`, `ID_COMERCIO`, `NOME`, `IMAGEM`, `PRECO`, `ESTOQUE`, `TIPO_VENDA`) VALUES ('1', '1', 'Laranja', 'orange', 'R$ 3,00', '30', 'Varejo');
INSERT INTO `produto` (`ID`, `ID_COMERCIO`, `NOME`, `IMAGEM`, `PRECO`, `ESTOQUE`, `TIPO_VENDA`) VALUES ('2', '1', 'Limão', 'lemon', 'R$ 2,00', '50', 'Encomenda');
INSERT INTO `valor_frete` (`ID`, `ID_FRETE`, `VALOR`, `DISTANCIA_LIMITE`) VALUES ('1', '1', 'R$2,00', '10 km');
INSERT INTO `venda` (`ID`, `ID_COMERCIO`, `ID_PRODUTO`, `TIPO`, `VALOR`, `DATA_PEDIDO`, `DATA_ENTREGA`, `VOLUME`, `QUANTIDADE`, `PAGAMENTO`) VALUES ('1', '1', '1', 'pedido', 'R$ 10,00', '11/02/2023', '11/02/2023', 'Kg', '1', 'Dinheiro');
INSERT INTO `venda` (`ID`, `ID_COMERCIO`, `ID_PRODUTO`, `TIPO`, `VALOR`, `DATA_PEDIDO`, `DATA_ENTREGA`, `VOLUME`, `QUANTIDADE`, `PAGAMENTO`) VALUES ('2', '1', '2', 'encomenda', 'R$ 50,00', '13/02/2023', '', 'Kg', '5', 'Cartão');


