CREATE TABLE `compre-local`.`comercio` (`ID` INT NOT NULL , `IMAGEM` VARCHAR NOT NULL , `ENDERECO` VARCHAR NOT NULL , `TELEFONE` VARCHAR NOT NULL , `HORARIO_ENTRADA` DATE NOT NULL , `HORARIO_SAIDA` DATE NOT NULL , `HORARIO_ENTRADA_TARDE` DATE NOT NULL , `HORARIO_SAIDA_TARDE` DATE NOT NULL , PRIMARY KEY (`ID`));
CREATE TABLE `compre-local`.`frete` (`ID` INT NOT NULL , `ID_COMERCIO` INT NOT NULL , `DISTANCIA_MAXIMA` VARCHAR(20) NOT NULL , `TIPO` VARCHAR(20) NOT NULL , PRIMARY KEY (`ID`));
CREATE TABLE `compre-local`.`valor_frete` (`ID` INT NOT NULL , `ID_FRETE` INT NOT NULL , `VALOR` VARCHAR(200) NOT NULL , `DISTANCIA_LIMITE` VARCHAR(200) NOT NULL , PRIMARY KEY (`ID`));
CREATE TABLE `compre-local`.`produto` (`ID` INT NOT NULL , `ID_COMERCIO` INT NOT NULL , `NOME` VARCHAR NOT NULL , `IMAGEM` VARCHAR(200) NOT NULL , `PRECO` VARCHAR(200) NOT NULL , `ESTOQUE` VARCHAR(200) NOT NULL , `TIPO_VENDA` VARCHAR(20) NOT NULL , PRIMARY KEY (`ID`));
CREATE TABLE `compre-local`.`venda` (`ID` INT NOT NULL , `ID_COMERCIO` INT NOT NULL , `ID_PRODUTO` INT NOT NULL , `TIPO` VARCHAR(20) NOT NULL , `VALOR` VARCHAR(200) NOT NULL , `DATA_PEDIDO` VARCHAR(200) NOT NULL , `DATA_ENTREGA` VARCHAR(200) NOT NULL , `VOLUME` VARCHAR(200) NOT NULL , `QUANTIDADE` VARCHAR(200) NOT NULL , `PAGAMENTO` VARCHAR(200) NOT NULL , PRIMARY KEY (`ID`));

/*INSERT*/

INSERT INTO `comercio` (`ID`, `IMAGEM`, `ENDERECO`, `TELEFONE`, `HORARIO_ENTRADA`, `HORARIO_SAIDA`, `HORARIO_ENTRADA_TARDE`, `HORARIO_SAIDA_TARDE`) VALUES ('1', 'capim_conveniencia', 'Rua dos trabalhadores, 15', '99-99999999', '08:00', '12:00', '13:00', '18:00');
INSERT INTO `venda` (`ID`, `ID_COMERCIO`, `ID_PRODUTO`, `TIPO`, `VALOR`, `DATA_PEDIDO`, `DATA_ENTREGA`, `VOLUME`, `QUANTIDADE`, `PAGAMENTO`) VALUES ('1', '1', '1', 'pedido', 'R$ 10,00', '11/02/2023', '11/02/2023', 'Kg', '1', 'Dinheiro'), ('2', '1', '2', 'Encomenda', 'R$ 50,00', '13/02/2023', '15/02/2023', 'Kg', '5', 'Cartão')
